/* ============================================================
   Peakbook: mountain dataset & curated lists
   Elevations in metres. Coordinates WGS84.
   ============================================================ */

const MOUNTAINS = [
  // ---- Eight-thousanders (14) ----
  { id: "everest",        name: "Mount Everest",      elevation: 8849, country: "Nepal / China",   flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.9881,  lng: 86.9250,   firstAscent: 1953 },
  { id: "k2",             name: "K2",                 elevation: 8611, country: "Pakistan / China",flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 35.8808,  lng: 76.5133,   firstAscent: 1954 },
  { id: "kangchenjunga",  name: "Kangchenjunga",      elevation: 8586, country: "Nepal / India",   flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.7025,  lng: 88.1475,   firstAscent: 1955 },
  { id: "lhotse",         name: "Lhotse",             elevation: 8516, country: "Nepal / China",   flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.9617,  lng: 86.9333,   firstAscent: 1956 },
  { id: "makalu",         name: "Makalu",             elevation: 8485, country: "Nepal / China",   flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.8897,  lng: 87.0889,   firstAscent: 1955 },
  { id: "cho-oyu",        name: "Cho Oyu",            elevation: 8188, country: "Nepal / China",   flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 28.0942,  lng: 86.6608,   firstAscent: 1954 },
  { id: "dhaulagiri",     name: "Dhaulagiri I",       elevation: 8167, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 28.6967,  lng: 83.4875,   firstAscent: 1960 },
  { id: "manaslu",        name: "Manaslu",            elevation: 8163, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 28.5497,  lng: 84.5597,   firstAscent: 1956 },
  { id: "nanga-parbat",   name: "Nanga Parbat",       elevation: 8126, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Himalaya",        lat: 35.2375,  lng: 74.5892,   firstAscent: 1953 },
  { id: "annapurna",      name: "Annapurna I",        elevation: 8091, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 28.5961,  lng: 83.8203,   firstAscent: 1950 },
  { id: "gasherbrum-1",   name: "Gasherbrum I",       elevation: 8080, country: "Pakistan / China",flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 35.7242,  lng: 76.6964,   firstAscent: 1958 },
  { id: "broad-peak",     name: "Broad Peak",         elevation: 8051, country: "Pakistan / China",flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 35.8117,  lng: 76.5650,   firstAscent: 1957 },
  { id: "gasherbrum-2",   name: "Gasherbrum II",      elevation: 8035, country: "Pakistan / China",flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 35.7578,  lng: 76.6531,   firstAscent: 1956 },
  { id: "shishapangma",   name: "Shishapangma",       elevation: 8027, country: "China",           flag: "🇨🇳", continent: "Asia",          range: "Himalaya",        lat: 28.3525,  lng: 85.7783,   firstAscent: 1964 },

  // ---- Seven Summits (incl. both Carstensz & Kosciuszko variants) ----
  { id: "aconcagua",      name: "Aconcagua",          elevation: 6961, country: "Argentina",       flag: "🇦🇷", continent: "South America", range: "Andes",           lat: -32.6532, lng: -70.0109,  firstAscent: 1897 },
  { id: "denali",         name: "Denali",             elevation: 6190, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Alaska Range",    lat: 63.0692,  lng: -151.0070, firstAscent: 1913 },
  { id: "kilimanjaro",    name: "Kilimanjaro",        elevation: 5895, country: "Tanzania",        flag: "🇹🇿", continent: "Africa",        range: "Rift Volcanoes",  lat: -3.0674,  lng: 37.3556,   firstAscent: 1889 },
  { id: "elbrus",         name: "Mount Elbrus",       elevation: 5642, country: "Russia",          flag: "🇷🇺", continent: "Europe",        range: "Caucasus",        lat: 43.3499,  lng: 42.4453,   firstAscent: 1874 },
  { id: "vinson",         name: "Mount Vinson",       elevation: 4892, country: "Antarctica",      flag: "🇦🇶", continent: "Antarctica",    range: "Ellsworth Mtns",  lat: -78.5254, lng: -85.6171,  firstAscent: 1966 },
  { id: "puncak-jaya",    name: "Puncak Jaya",        elevation: 4884, country: "Indonesia",       flag: "🇮🇩", continent: "Oceania",       range: "Sudirman Range",  lat: -4.0833,  lng: 137.1833,  firstAscent: 1962 },
  { id: "kosciuszko",     name: "Mount Kosciuszko",   elevation: 2228, country: "Australia",       flag: "🇦🇺", continent: "Oceania",       range: "Snowy Mountains", lat: -36.4558, lng: 148.2636,  firstAscent: 1840 },

  // ---- Volcanic Seven Summits (remaining) ----
  { id: "ojos",           name: "Ojos del Salado",    elevation: 6893, country: "Chile / Argentina",flag: "🇨🇱", continent: "South America", range: "Andes",          lat: -27.1092, lng: -68.5414,  firstAscent: 1937 },
  { id: "orizaba",        name: "Pico de Orizaba",    elevation: 5636, country: "Mexico",          flag: "🇲🇽", continent: "North America", range: "Trans-Mexican Belt", lat: 19.0303, lng: -97.2697, firstAscent: 1848 },
  { id: "damavand",       name: "Mount Damavand",     elevation: 5610, country: "Iran",            flag: "🇮🇷", continent: "Asia",          range: "Alborz",          lat: 35.9550,  lng: 52.1100,   firstAscent: 1837 },
  { id: "giluwe",         name: "Mount Giluwe",       elevation: 4367, country: "Papua New Guinea",flag: "🇵🇬", continent: "Oceania",       range: "Southern Highlands", lat: -6.0433, lng: 143.8869, firstAscent: 1934 },
  { id: "sidley",         name: "Mount Sidley",       elevation: 4285, country: "Antarctica",      flag: "🇦🇶", continent: "Antarctica",    range: "Executive Committee", lat: -77.0333, lng: -126.1000, firstAscent: 1990 },

  // ---- Alpine classics ----
  { id: "mont-blanc",     name: "Mont Blanc",         elevation: 4808, country: "France / Italy",  flag: "🇫🇷", continent: "Europe",        range: "Alps",            lat: 45.8326,  lng: 6.8652,    firstAscent: 1786 },
  { id: "dufourspitze",   name: "Dufourspitze",       elevation: 4634, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 45.9369,  lng: 7.8672,    firstAscent: 1855 },
  { id: "dom",            name: "Dom",                elevation: 4545, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.0942,  lng: 7.8586,    firstAscent: 1858 },
  { id: "lyskamm",        name: "Lyskamm",            elevation: 4527, country: "Switzerland / Italy", flag: "🇨🇭", continent: "Europe",    range: "Alps",            lat: 45.9222,  lng: 7.8358,    firstAscent: 1861 },
  { id: "weisshorn",      name: "Weisshorn",          elevation: 4506, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.1014,  lng: 7.7158,    firstAscent: 1861 },
  { id: "matterhorn",     name: "Matterhorn",         elevation: 4478, country: "Switzerland / Italy", flag: "🇨🇭", continent: "Europe",    range: "Alps",            lat: 45.9764,  lng: 7.6586,    firstAscent: 1865 },
  { id: "dent-blanche",   name: "Dent Blanche",       elevation: 4357, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.0342,  lng: 7.6119,    firstAscent: 1862 },
  { id: "grand-combin",   name: "Grand Combin",       elevation: 4314, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 45.9375,  lng: 7.2986,    firstAscent: 1859 },
  { id: "finsteraarhorn", name: "Finsteraarhorn",     elevation: 4274, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.5372,  lng: 8.1261,    firstAscent: 1829 },
  { id: "grandes-jorasses", name: "Grandes Jorasses", elevation: 4208, country: "France / Italy",  flag: "🇫🇷", continent: "Europe",        range: "Alps",            lat: 45.8686,  lng: 6.9861,    firstAscent: 1868 },
  { id: "breithorn",      name: "Breithorn",          elevation: 4164, country: "Switzerland / Italy", flag: "🇨🇭", continent: "Europe",    range: "Alps",            lat: 45.9414,  lng: 7.7314,    firstAscent: 1813 },
  { id: "aiguille-verte", name: "Aiguille Verte",     elevation: 4122, country: "France",          flag: "🇫🇷", continent: "Europe",        range: "Alps",            lat: 45.9342,  lng: 6.9631,    firstAscent: 1865 },
  { id: "barre-ecrins",   name: "Barre des Écrins",   elevation: 4102, country: "France",          flag: "🇫🇷", continent: "Europe",        range: "Alps",            lat: 44.9219,  lng: 6.3567,    firstAscent: 1864 },
  { id: "jungfrau",       name: "Jungfrau",           elevation: 4158, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.5367,  lng: 7.9625,    firstAscent: 1811 },
  { id: "monch",          name: "Mönch",              elevation: 4107, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.5583,  lng: 7.9978,    firstAscent: 1857 },
  { id: "piz-bernina",    name: "Piz Bernina",        elevation: 4049, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.3822,  lng: 9.9081,    firstAscent: 1850 },
  { id: "gran-paradiso",  name: "Gran Paradiso",      elevation: 4061, country: "Italy",           flag: "🇮🇹", continent: "Europe",        range: "Alps",            lat: 45.5175,  lng: 7.2669,    firstAscent: 1860 },
  { id: "eiger",          name: "Eiger",              elevation: 3967, country: "Switzerland",     flag: "🇨🇭", continent: "Europe",        range: "Alps",            lat: 46.5775,  lng: 8.0053,    firstAscent: 1858 },
  { id: "ortler",         name: "Ortler",             elevation: 3905, country: "Italy",           flag: "🇮🇹", continent: "Europe",        range: "Alps",            lat: 46.5089,  lng: 10.5447,   firstAscent: 1804 },
  { id: "wildspitze",     name: "Wildspitze",         elevation: 3768, country: "Austria",         flag: "🇦🇹", continent: "Europe",        range: "Ötztal Alps",     lat: 46.8853,  lng: 10.8672,   firstAscent: 1848 },
  { id: "grossglockner",  name: "Grossglockner",      elevation: 3798, country: "Austria",         flag: "🇦🇹", continent: "Europe",        range: "Alps",            lat: 47.0742,  lng: 12.6947,   firstAscent: 1800 },
  { id: "marmolada",      name: "Marmolada",          elevation: 3343, country: "Italy",           flag: "🇮🇹", continent: "Europe",        range: "Dolomites",       lat: 46.4344,  lng: 11.8514,   firstAscent: 1864 },
  { id: "cima-grande",    name: "Cima Grande di Lavaredo", elevation: 2999, country: "Italy",      flag: "🇮🇹", continent: "Europe",        range: "Dolomites",       lat: 46.6186,  lng: 12.3053,   firstAscent: 1869 },
  { id: "zugspitze",      name: "Zugspitze",          elevation: 2962, country: "Germany",         flag: "🇩🇪", continent: "Europe",        range: "Alps",            lat: 47.4211,  lng: 10.9853,   firstAscent: 1820 },
  { id: "triglav",        name: "Triglav",            elevation: 2864, country: "Slovenia",        flag: "🇸🇮", continent: "Europe",        range: "Julian Alps",     lat: 46.3783,  lng: 13.8367,   firstAscent: 1778 },
  { id: "watzmann",       name: "Watzmann",           elevation: 2713, country: "Germany",         flag: "🇩🇪", continent: "Europe",        range: "Berchtesgaden Alps", lat: 47.5553, lng: 12.9225,  firstAscent: 1800 },

  // ---- Cascade & West-coast volcanoes ----
  { id: "rainier",        name: "Mount Rainier",      elevation: 4392, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 46.8523,  lng: -121.7603, firstAscent: 1870 },
  { id: "shasta",         name: "Mount Shasta",       elevation: 4322, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 41.4092,  lng: -122.1949, firstAscent: 1854 },
  { id: "adams",          name: "Mount Adams",        elevation: 3743, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 46.2024,  lng: -121.4909, firstAscent: 1854 },
  { id: "hood",           name: "Mount Hood",         elevation: 3429, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 45.3735,  lng: -121.6959, firstAscent: 1857 },
  { id: "baker",          name: "Mount Baker",        elevation: 3286, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 48.7768,  lng: -121.8145, firstAscent: 1868 },
  { id: "glacier-peak",   name: "Glacier Peak",       elevation: 3213, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 48.1121,  lng: -121.1132, firstAscent: 1898 },
  { id: "jefferson",      name: "Mount Jefferson",    elevation: 3199, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 44.6743,  lng: -121.7996, firstAscent: 1888 },
  { id: "south-sister",   name: "South Sister",       elevation: 3157, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 44.1035,  lng: -121.7693, firstAscent: 1866 },
  { id: "st-helens",      name: "Mount St. Helens",   elevation: 2549, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 46.1914,  lng: -122.1956, firstAscent: 1853 },
  { id: "lassen",         name: "Lassen Peak",        elevation: 3187, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Cascades",        lat: 40.4882,  lng: -121.5050, firstAscent: 1851 },

  // ---- US classics ----
  { id: "whitney",        name: "Mount Whitney",      elevation: 4421, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sierra Nevada",   lat: 36.5785,  lng: -118.2923, firstAscent: 1873 },
  { id: "elbert",         name: "Mount Elbert",       elevation: 4401, ft: 14440, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",   lat: 39.1178,  lng: -106.4454, firstAscent: 1874 },
  { id: "longs",          name: "Longs Peak",         elevation: 4346, ft: 14259, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Front Range",     lat: 40.2549,  lng: -105.6151, firstAscent: 1868 },
  { id: "saint-elias",    name: "Mount Saint Elias",  elevation: 5489, country: "United States / Canada", flag: "🇺🇸", continent: "North America", range: "Saint Elias Mtns", lat: 60.2931, lng: -140.9311, firstAscent: 1897 },
  { id: "foraker",        name: "Mount Foraker",      elevation: 5304, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Alaska Range",    lat: 62.9605,  lng: -151.3997, firstAscent: 1934 },
  { id: "gannett",        name: "Gannett Peak",       elevation: 4209, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Wind River Range", lat: 43.1842, lng: -109.6542, firstAscent: 1922 },
  { id: "grand-teton",    name: "Grand Teton",        elevation: 4199, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Teton Range",     lat: 43.7412,  lng: -110.8024, firstAscent: 1898 },
  { id: "shuksan",        name: "Mount Shuksan",      elevation: 2783, ft: 9131,  country: "United States",   flag: "🇺🇸", continent: "North America", range: "North Cascades",  lat: 48.8317,  lng: -121.6031, firstAscent: 1906 },
  { id: "humphreys",      name: "Humphreys Peak",     elevation: 3852, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Francisco Peaks", lat: 35.3464, lng: -111.6780 },
  { id: "mauna-kea",      name: "Mauna Kea",          elevation: 4207, country: "United States",   flag: "🇺🇸", continent: "Oceania",       range: "Hawaiʻi",         lat: 19.8206,  lng: -155.4681 },
  { id: "mauna-loa",      name: "Mauna Loa",          elevation: 4169, country: "United States",   flag: "🇺🇸", continent: "Oceania",       range: "Hawaiʻi",         lat: 19.4756,  lng: -155.6054 },
  { id: "haleakala",      name: "Haleakalā",          elevation: 3055, country: "United States",   flag: "🇺🇸", continent: "Oceania",       range: "Hawaiʻi",         lat: 20.7097,  lng: -156.2533 },
  { id: "half-dome",      name: "Half Dome",          elevation: 2694, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sierra Nevada",   lat: 37.7459,  lng: -119.5332, firstAscent: 1875 },
  { id: "el-capitan",     name: "El Capitan",         elevation: 2307, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sierra Nevada",   lat: 37.7340,  lng: -119.6377, firstAscent: 1958 },
  { id: "mitchell",       name: "Mount Mitchell",     elevation: 2037, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Appalachians",    lat: 35.7648,  lng: -82.2652,  firstAscent: 1835 },
  { id: "marcy",          name: "Mount Marcy",        elevation: 1629, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Adirondacks",     lat: 44.1126,  lng: -73.9236,  firstAscent: 1837 },
  { id: "katahdin",       name: "Mount Katahdin",     elevation: 1606, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Appalachians",    lat: 45.9044,  lng: -68.9213, firstAscent: 1804 },
  { id: "washington-nh",  name: "Mount Washington",   elevation: 1917, country: "United States",   flag: "🇺🇸", continent: "North America", range: "White Mountains", lat: 44.2705,  lng: -71.3033, firstAscent: 1642 },

  // ---- Colorado 14ers (Mount Elbert & Longs Peak are listed above) ----
  { id: "massive",          name: "Mount Massive",          elevation: 4398, ft: 14428, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 39.1875, lng: -106.4757 },
  { id: "harvard",          name: "Mount Harvard",          elevation: 4396, ft: 14421, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.9244, lng: -106.3207 },
  { id: "blanca",           name: "Blanca Peak",            elevation: 4374, ft: 14351, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.5775, lng: -105.4856 },
  { id: "la-plata",         name: "La Plata Peak",          elevation: 4372, ft: 14343, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 39.0294, lng: -106.4729 },
  { id: "uncompahgre",      name: "Uncompahgre Peak",       elevation: 4365, ft: 14321, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 38.0717, lng: -107.4621 },
  { id: "crestone-peak",    name: "Crestone Peak",          elevation: 4359, ft: 14300, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.9669, lng: -105.5855 },
  { id: "lincoln",          name: "Mount Lincoln",          elevation: 4357, ft: 14293, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Mosquito Range",    lat: 39.3515, lng: -106.1116 },
  { id: "castle-peak",      name: "Castle Peak",            elevation: 4352, ft: 14279, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.0097, lng: -106.8614 },
  { id: "grays",            name: "Grays Peak",             elevation: 4352, ft: 14278, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Front Range",       lat: 39.6339, lng: -105.8176 },
  { id: "antero",           name: "Mount Antero",           elevation: 4351, ft: 14276, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.6741, lng: -106.2462 },
  { id: "torreys",          name: "Torreys Peak",           elevation: 4351, ft: 14275, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Front Range",       lat: 39.6428, lng: -105.8212 },
  { id: "quandary",         name: "Quandary Peak",          elevation: 4350, ft: 14271, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Tenmile Range",     lat: 39.3973, lng: -106.1064 },
  { id: "blue-sky",         name: "Mount Blue Sky",         elevation: 4350, ft: 14271, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Front Range",       lat: 39.5883, lng: -105.6438, aka: "Mount Evans" },
  { id: "mt-wilson",        name: "Mount Wilson",           elevation: 4344, ft: 14252, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.8391, lng: -107.9916 },
  { id: "cameron",          name: "Mount Cameron",          elevation: 4340, ft: 14238, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Mosquito Range",    lat: 39.3464, lng: -106.1187 },
  { id: "shavano",          name: "Mount Shavano",          elevation: 4338, ft: 14231, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.6192, lng: -106.2393 },
  { id: "princeton",        name: "Mount Princeton",        elevation: 4329, ft: 14204, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.7492, lng: -106.2424 },
  { id: "belford",          name: "Mount Belford",          elevation: 4329, ft: 14203, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.9607, lng: -106.3607 },
  { id: "crestone-needle",  name: "Crestone Needle",        elevation: 4329, ft: 14203, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.9647, lng: -105.5766 },
  { id: "yale",             name: "Mount Yale",             elevation: 4328, ft: 14200, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.8442, lng: -106.3138 },
  { id: "bross",            name: "Mount Bross",            elevation: 4322, ft: 14178, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Mosquito Range",    lat: 39.3354, lng: -106.1077 },
  { id: "kit-carson",       name: "Kit Carson Peak",        elevation: 4319, ft: 14171, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.9797, lng: -105.6026 },
  { id: "maroon-peak",      name: "Maroon Peak",            elevation: 4317, ft: 14163, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.0708, lng: -106.9890, aka: "South Maroon Peak Maroon Bells" },
  { id: "tabeguache",       name: "Tabeguache Peak",        elevation: 4317, ft: 14162, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.6255, lng: -106.2509 },
  { id: "el-diente",        name: "El Diente Peak",         elevation: 4316, ft: 14159, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.8394, lng: -108.0060 },
  { id: "oxford",           name: "Mount Oxford",           elevation: 4316, ft: 14160, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.9648, lng: -106.3388 },
  { id: "sneffels",         name: "Mount Sneffels",         elevation: 4315, ft: 14158, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 38.0038, lng: -107.7923 },
  { id: "democrat",         name: "Mount Democrat",         elevation: 4315, ft: 14155, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Mosquito Range",    lat: 39.3396, lng: -106.1400 },
  { id: "capitol",          name: "Capitol Peak",           elevation: 4309, ft: 14137, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.1503, lng: -107.0829 },
  { id: "pikes",            name: "Pikes Peak",             elevation: 4302, ft: 14115, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Front Range",       lat: 38.8405, lng: -105.0442, firstAscent: 1820 },
  { id: "snowmass",         name: "Snowmass Mountain",      elevation: 4297, ft: 14099, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.1188, lng: -107.0665 },
  { id: "windom",           name: "Windom Peak",            elevation: 4296, ft: 14093, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.6212, lng: -107.5919 },
  { id: "eolus",            name: "Mount Eolus",            elevation: 4295, ft: 14090, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.6218, lng: -107.6227 },
  { id: "challenger",       name: "Challenger Point",       elevation: 4294, ft: 14087, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.9804, lng: -105.6066 },
  { id: "columbia",         name: "Mount Columbia",         elevation: 4291, ft: 14077, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.9039, lng: -106.2975 },
  { id: "missouri",         name: "Missouri Mountain",      elevation: 4290, ft: 14074, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.9476, lng: -106.3785 },
  { id: "humboldt",         name: "Humboldt Peak",          elevation: 4289, ft: 14070, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.9762, lng: -105.5552 },
  { id: "bierstadt",        name: "Mount Bierstadt",        elevation: 4287, ft: 14065, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Front Range",       lat: 39.5826, lng: -105.6688 },
  { id: "sunlight",         name: "Sunlight Peak",          elevation: 4287, ft: 14065, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.6274, lng: -107.5959 },
  { id: "conundrum",        name: "Conundrum Peak",         elevation: 4285, ft: 14060, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.0157, lng: -106.8628 },
  { id: "handies",          name: "Handies Peak",           elevation: 4285, ft: 14058, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.9130, lng: -107.5044 },
  { id: "culebra",          name: "Culebra Peak",           elevation: 4283, ft: 14053, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.1224, lng: -105.1858 },
  { id: "ellingwood",       name: "Ellingwood Point",       elevation: 4282, ft: 14048, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.5826, lng: -105.4927 },
  { id: "lindsey",          name: "Mount Lindsey",          elevation: 4282, ft: 14048, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.5837, lng: -105.4449 },
  { id: "little-bear",      name: "Little Bear Peak",       elevation: 4280, ft: 14043, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sangre de Cristo",  lat: 37.5666, lng: -105.4972 },
  { id: "sherman",          name: "Mount Sherman",          elevation: 4280, ft: 14043, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Mosquito Range",    lat: 39.2250, lng: -106.1699 },
  { id: "redcloud",         name: "Redcloud Peak",          elevation: 4280, ft: 14041, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.9410, lng: -107.4219 },
  { id: "north-eolus",      name: "North Eolus",            elevation: 4279, ft: 14039, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.6252, lng: -107.6212 },
  { id: "pyramid",          name: "Pyramid Peak",           elevation: 4275, ft: 14025, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.0717, lng: -106.9502 },
  { id: "wilson-peak",      name: "Wilson Peak",            elevation: 4274, ft: 14023, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.8603, lng: -107.9847 },
  { id: "san-luis",         name: "San Luis Peak",          elevation: 4274, ft: 14022, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.9868, lng: -106.9313 },
  { id: "wetterhorn",       name: "Wetterhorn Peak",        elevation: 4274, ft: 14021, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 38.0607, lng: -107.5109 },
  { id: "north-maroon",     name: "North Maroon Peak",      elevation: 4272, ft: 14014, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Elk Mountains",     lat: 39.0760, lng: -106.9871 },
  { id: "holy-cross",       name: "Mount of the Holy Cross",elevation: 4271, ft: 14011, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 39.4668, lng: -106.4817 },
  { id: "huron",            name: "Huron Peak",             elevation: 4270, ft: 14010, country: "United States",   flag: "🇺🇸", continent: "North America", range: "Sawatch Range",     lat: 38.9455, lng: -106.4381 },
  { id: "sunshine",         name: "Sunshine Peak",          elevation: 4270, ft: 14007, country: "United States",   flag: "🇺🇸", continent: "North America", range: "San Juan Mountains",lat: 37.9228, lng: -107.4256 },

  // ---- Andes & South America ----
  { id: "pissis",         name: "Monte Pissis",       elevation: 6793, country: "Argentina",       flag: "🇦🇷", continent: "South America", range: "Andes",           lat: -27.7550, lng: -68.8000,  firstAscent: 1937 },
  { id: "mercedario",     name: "Mercedario",         elevation: 6770, country: "Argentina",       flag: "🇦🇷", continent: "South America", range: "Cordillera de la Ramada", lat: -31.9792, lng: -70.1125,  firstAscent: 1934 },
  { id: "huascaran",      name: "Huascarán",          elevation: 6768, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.1219, lng: -77.6042, firstAscent: 1932 },
  { id: "llullaillaco",   name: "Llullaillaco",       elevation: 6739, country: "Chile / Argentina", flag: "🇨🇱", continent: "South America", range: "Andes",         lat: -24.7208, lng: -68.5367 },
  { id: "yerupaja",       name: "Yerupajá",           elevation: 6635, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Huayhuash", lat: -10.2833, lng: -76.9167, firstAscent: 1950 },
  { id: "tupungato",      name: "Tupungato",          elevation: 6570, country: "Argentina / Chile", flag: "🇦🇷", continent: "South America", range: "Andes",           lat: -33.3583, lng: -69.7700,  firstAscent: 1897 },
  { id: "sajama",         name: "Nevado Sajama",      elevation: 6542, country: "Bolivia",         flag: "🇧🇴", continent: "South America", range: "Andes",           lat: -18.1064, lng: -68.8836,  firstAscent: 1927 },
  { id: "illimani",       name: "Illimani",           elevation: 6438, country: "Bolivia",         flag: "🇧🇴", continent: "South America", range: "Cordillera Real", lat: -16.6533, lng: -67.7900,  firstAscent: 1898 },
  { id: "ancohuma",       name: "Ancohuma",           elevation: 6427, country: "Bolivia",         flag: "🇧🇴", continent: "South America", range: "Cordillera Real", lat: -15.8533, lng: -68.5408,  firstAscent: 1919 },
  { id: "huandoy",        name: "Huandoy",            elevation: 6395, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.0286,  lng: -77.6656,  firstAscent: 1932 },
  { id: "ausangate",      name: "Ausangate",          elevation: 6384, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Vilcanota", lat: -13.7886, lng: -71.2311,  firstAscent: 1953 },
  { id: "parinacota",     name: "Parinacota",         elevation: 6380, country: "Chile / Bolivia", flag: "🇨🇱", continent: "South America", range: "Andes",           lat: -18.1661, lng: -69.1419,  firstAscent: 1928 },
  { id: "coropuna",       name: "Nevado Coropuna",    elevation: 6377, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Andes",           lat: -15.5500, lng: -72.6500,  firstAscent: 1952 },
  { id: "chopicalqui",    name: "Chopicalqui",        elevation: 6354, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.0867,  lng: -77.5739,  firstAscent: 1932 },
  { id: "siula-grande",   name: "Siula Grande",       elevation: 6344, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Huayhuash", lat: -10.2861, lng: -76.8919, firstAscent: 1936 },
  { id: "salcantay",      name: "Salcantay",          elevation: 6271, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Vilcabamba", lat: -13.3336, lng: -72.5444,  firstAscent: 1952 },
  { id: "chimborazo",     name: "Chimborazo",         elevation: 6263, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: -1.4692,  lng: -78.8175,  firstAscent: 1880 },
  { id: "ranrapalca",     name: "Ranrapalca",         elevation: 6162, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.4109,  lng: -77.4167,  firstAscent: 1939 },
  { id: "chacraraju",     name: "Chacraraju",         elevation: 6108, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -8.9933,  lng: -77.6150,  firstAscent: 1956 },
  { id: "huayna-potosi",  name: "Huayna Potosí",      elevation: 6088, country: "Bolivia",         flag: "🇧🇴", continent: "South America", range: "Cordillera Real", lat: -16.2661, lng: -68.1533,  firstAscent: 1919 },
  { id: "chachani",       name: "Chachani",           elevation: 6057, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Andes",           lat: -16.1833, lng: -71.5167 },
  { id: "tocllaraju",     name: "Tocllaraju",         elevation: 6034, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.3476,  lng: -77.3968,  firstAscent: 1939 },
  { id: "artesonraju",    name: "Artesonraju",        elevation: 6025, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -8.9500,  lng: -77.6333,  firstAscent: 1932 },
  { id: "alpamayo",       name: "Alpamayo",           elevation: 5947, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -8.8786, lng: -77.6536, firstAscent: 1957 },
  { id: "licancabur",     name: "Licancabur",         elevation: 5916, country: "Chile / Bolivia", flag: "🇨🇱", continent: "South America", range: "Andes",           lat: -22.8339, lng: -67.8836 },
  { id: "cotopaxi",       name: "Cotopaxi",           elevation: 5897, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: -0.6809,  lng: -78.4378,  firstAscent: 1872 },
  { id: "misti",          name: "El Misti",           elevation: 5822, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Andes",           lat: -16.2942, lng: -71.4092 },
  { id: "cayambe",        name: "Cayambe",            elevation: 5790, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: 0.0292,   lng: -77.9867,  firstAscent: 1880 },
  { id: "antisana",       name: "Antisana",           elevation: 5753, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: -0.4814,  lng: -78.1408,  firstAscent: 1880 },
  { id: "pisco",          name: "Nevado Pisco",       elevation: 5752, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.0118,  lng: -77.6311,  firstAscent: 1951 },
  { id: "cristobal-colon", name: "Pico Cristóbal Colón", elevation: 5730, country: "Colombia",     flag: "🇨🇴", continent: "South America", range: "Sierra Nevada de Santa Marta", lat: 10.8383, lng: -73.6861, firstAscent: 1939 },
  { id: "vallunaraju",    name: "Vallunaraju",        elevation: 5686, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.4222,  lng: -77.4564,  firstAscent: 1949 },
  { id: "ishinca",        name: "Nevado Ishinca",     elevation: 5530, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.3886,  lng: -77.4036,  firstAscent: 1964 },
  { id: "sangay",         name: "Sangay",             elevation: 5286, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: -2.0025,  lng: -78.3408,  firstAscent: 1929 },
  { id: "illiniza-sur",   name: "Illiniza Sur",       elevation: 5248, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: -0.6594,  lng: -78.7136,  firstAscent: 1880 },
  { id: "nevado-mateo",   name: "Nevado Mateo",       elevation: 5150, country: "Peru",            flag: "🇵🇪", continent: "South America", range: "Cordillera Blanca", lat: -9.1063, lng: -77.4935 },
  { id: "tungurahua",     name: "Tungurahua",         elevation: 5023, country: "Ecuador",         flag: "🇪🇨", continent: "South America", range: "Andes",           lat: -1.4700,  lng: -78.4447,  firstAscent: 1873 },
  { id: "pico-bolivar",   name: "Pico Bolívar",       elevation: 4978, country: "Venezuela",       flag: "🇻🇪", continent: "South America", range: "Cordillera de Mérida", lat: 8.5411, lng: -71.0472,  firstAscent: 1935 },
  { id: "lanin",          name: "Volcán Lanín",       elevation: 3776, country: "Argentina / Chile", flag: "🇦🇷", continent: "South America", range: "Andes",           lat: -39.6328, lng: -71.4997,  firstAscent: 1897 },
  { id: "san-lorenzo",    name: "Monte San Lorenzo",  elevation: 3706, country: "Argentina / Chile", flag: "🇦🇷", continent: "South America", range: "Patagonia",       lat: -47.5833, lng: -72.3000,  firstAscent: 1943 },
  { id: "fitz-roy",       name: "Fitz Roy",           elevation: 3405, country: "Argentina / Chile", flag: "🇦🇷", continent: "South America", range: "Patagonia",     lat: -49.2711, lng: -73.0433,  firstAscent: 1952 },
  { id: "cerro-torre",    name: "Cerro Torre",        elevation: 3128, country: "Argentina / Chile", flag: "🇦🇷", continent: "South America", range: "Patagonia",     lat: -49.2925, lng: -73.0983,  firstAscent: 1974 },
  { id: "neblina",        name: "Pico da Neblina",    elevation: 2995, country: "Brazil",          flag: "🇧🇷", continent: "South America", range: "Serra do Imeri",  lat: 0.8025,   lng: -66.0092,  firstAscent: 1965 },
  { id: "paine-grande",   name: "Cerro Paine Grande", elevation: 2884, country: "Chile",           flag: "🇨🇱", continent: "South America", range: "Patagonia",       lat: -50.9950, lng: -73.0867,  firstAscent: 1957 },
  { id: "villarrica",     name: "Villarrica",         elevation: 2847, country: "Chile",           flag: "🇨🇱", continent: "South America", range: "Andes",           lat: -39.4200, lng: -71.9394 },
  { id: "roraima",        name: "Mount Roraima",      elevation: 2810, country: "Venezuela / Brazil / Guyana", flag: "🇻🇪", continent: "South America", range: "Pakaraima Mtns", lat: 5.1436, lng: -60.7625, firstAscent: 1884 },
  { id: "torres-paine",   name: "Torres del Paine",   elevation: 2500, country: "Chile",           flag: "🇨🇱", continent: "South America", range: "Patagonia",       lat: -50.9423, lng: -72.9986,  firstAscent: 1963 },
  { id: "sarmiento",      name: "Monte Sarmiento",    elevation: 2246, country: "Chile",           flag: "🇨🇱", continent: "South America", range: "Tierra del Fuego", lat: -54.4500, lng: -70.8333,  firstAscent: 1956 },
  { id: "julianatop",     name: "Julianatop",         elevation: 1280, country: "Suriname",        flag: "🇸🇷", continent: "South America", range: "Wilhelmina Mtns", lat: 3.6828,   lng: -56.5356 },

  // ---- Asian 7,000ers & sacred summits ----
  { id: "distaghil-sar",  name: "Distaghil Sar",      elevation: 7885, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 36.3258,  lng: 75.1883,   firstAscent: 1960 },
  { id: "kunyang-chhish", name: "Kunyang Chhish",     elevation: 7852, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 36.2053,  lng: 75.2078,   firstAscent: 1971 },
  { id: "masherbrum",     name: "Masherbrum (K1)",    elevation: 7821, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 35.6411,  lng: 76.3047,   firstAscent: 1960 },
  { id: "nanda-devi",     name: "Nanda Devi",         elevation: 7816, country: "India",           flag: "🇮🇳", continent: "Asia",          range: "Garhwal Himalaya", lat: 30.3767, lng: 79.9708,   firstAscent: 1936 },
  { id: "batura-sar",     name: "Batura Sar",         elevation: 7795, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 36.5100,  lng: 74.5225,   firstAscent: 1976 },
  { id: "rakaposhi",      name: "Rakaposhi",          elevation: 7788, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 36.1425,  lng: 74.4894,   firstAscent: 1958 },
  { id: "namcha-barwa",   name: "Namcha Barwa",       elevation: 7782, country: "China",           flag: "🇨🇳", continent: "Asia",          range: "Himalaya",        lat: 29.6306,  lng: 95.0553,   firstAscent: 1992 },
  { id: "tirich-mir",     name: "Tirich Mir",         elevation: 7708, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Hindu Kush",      lat: 36.2542,  lng: 71.8433,   firstAscent: 1950 },
  { id: "gangkhar-puensum", name: "Gangkhar Puensum", elevation: 7570, country: "Bhutan / China",  flag: "🇧🇹", continent: "Asia",          range: "Himalaya",        lat: 28.0472,  lng: 90.4556 },
  { id: "gongga-shan",    name: "Gongga Shan",        elevation: 7556, country: "China",           flag: "🇨🇳", continent: "Asia",          range: "Daxue Shan",      lat: 29.5953,  lng: 101.8797,  firstAscent: 1932 },
  { id: "muztagh-ata",    name: "Muztagh Ata",        elevation: 7546, country: "China",           flag: "🇨🇳", continent: "Asia",          range: "Pamir",           lat: 38.2775,  lng: 75.1156,   firstAscent: 1956 },
  { id: "ismoil-somoni",  name: "Ismoil Somoni Peak", elevation: 7495, country: "Tajikistan",      flag: "🇹🇯", continent: "Asia",          range: "Pamir",           lat: 38.9403,  lng: 72.0161,   firstAscent: 1933 },
  { id: "noshaq",         name: "Noshaq",             elevation: 7492, country: "Afghanistan / Pakistan", flag: "🇦🇫", continent: "Asia",          range: "Hindu Kush",      lat: 36.4317,  lng: 71.8283,   firstAscent: 1960 },
  { id: "jengish-chokusu", name: "Jengish Chokusu",   elevation: 7439, country: "Kyrgyzstan / China", flag: "🇰🇬", continent: "Asia",       range: "Tian Shan",       lat: 42.0361,  lng: 80.1181,   firstAscent: 1956 },
  { id: "pumori",         name: "Pumori",             elevation: 7161, country: "Nepal / China",   flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 28.0147,  lng: 86.8250,   firstAscent: 1962 },
  { id: "baruntse",       name: "Baruntse",           elevation: 7129, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.8722,  lng: 86.9800,   firstAscent: 1954 },
  { id: "korzhenevskaya", name: "Peak Korzhenevskaya", elevation: 7105, country: "Tajikistan",      flag: "🇹🇯", continent: "Asia",          range: "Pamir",           lat: 39.0575,  lng: 72.0083,   firstAscent: 1953, aka: "Peak Ozodi Pik Korzhenevskoi" },
  { id: "machapuchare",   name: "Machapuchare",       elevation: 6993, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Annapurna Himal", lat: 28.4956,  lng: 83.9494 },
  { id: "kailash",        name: "Mount Kailash",      elevation: 6638, country: "China",           flag: "🇨🇳", continent: "Asia",          range: "Gangdise",        lat: 31.0678,  lng: 81.3119 },
  { id: "shivling",       name: "Shivling",           elevation: 6543, country: "India",           flag: "🇮🇳", continent: "Asia",          range: "Garhwal Himalaya", lat: 30.8767, lng: 79.0656,   firstAscent: 1974 },
  { id: "trango-tower",   name: "Trango Tower",       elevation: 6239, country: "Pakistan",        flag: "🇵🇰", continent: "Asia",          range: "Karakoram",       lat: 35.8497,  lng: 76.1861,   firstAscent: 1976 },

  // ---- Himalaya & Asia trekking classics ----
  { id: "ama-dablam",     name: "Ama Dablam",         elevation: 6812, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.8617,  lng: 86.8614,   firstAscent: 1961 },
  { id: "mera-peak",      name: "Mera Peak",          elevation: 6476, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.7089,  lng: 86.8675,   firstAscent: 1953 },
  { id: "island-peak",    name: "Island Peak",        elevation: 6189, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.9219,  lng: 86.9364,   firstAscent: 1953 },
  { id: "lobuche-east",   name: "Lobuche East",       elevation: 6119, country: "Nepal",           flag: "🇳🇵", continent: "Asia",          range: "Himalaya",        lat: 27.9600,  lng: 86.7900,   firstAscent: 1984 },
  { id: "khan-tengri",    name: "Khan Tengri",        elevation: 7010, country: "Kazakhstan / Kyrgyzstan", flag: "🇰🇿", continent: "Asia",  range: "Tian Shan",       lat: 42.2133,  lng: 80.1742,   firstAscent: 1931 },
  { id: "lenin-peak",     name: "Lenin Peak",         elevation: 7134, country: "Kyrgyzstan / Tajikistan", flag: "🇰🇬", continent: "Asia",  range: "Pamir",           lat: 39.3428,  lng: 72.8781,   firstAscent: 1928 },
  { id: "hkakabo-razi",   name: "Hkakabo Razi",       elevation: 5881, country: "Myanmar",         flag: "🇲🇲", continent: "Asia",          range: "Himalaya",        lat: 28.3283,  lng: 97.5356,   firstAscent: 1996 },
  { id: "shkhara",        name: "Shkhara",            elevation: 5193, country: "Georgia",         flag: "🇬🇪", continent: "Asia",          range: "Caucasus",        lat: 43.0006,  lng: 43.1122,   firstAscent: 1888 },
  { id: "kazbek",         name: "Mount Kazbek",       elevation: 5054, country: "Georgia / Russia",flag: "🇬🇪", continent: "Asia",          range: "Caucasus",        lat: 42.6961,  lng: 44.5200,   firstAscent: 1868 },
  { id: "ushba",          name: "Ushba",              elevation: 4710, country: "Georgia",         flag: "🇬🇪", continent: "Asia",          range: "Caucasus",        lat: 43.1247,  lng: 42.6589,   firstAscent: 1888 },
  { id: "ararat",         name: "Mount Ararat",       elevation: 5137, country: "Türkiye",         flag: "🇹🇷", continent: "Asia",          range: "Armenian Highlands", lat: 39.7019, lng: 44.2983,  firstAscent: 1829 },
  { id: "klyuchevskaya",  name: "Klyuchevskaya Sopka", elevation: 4754, country: "Russia",          flag: "🇷🇺", continent: "Asia",          range: "Kamchatka",       lat: 56.0561,  lng: 160.6442,  firstAscent: 1788 },
  { id: "khazret-sultan", name: "Khazret Sultan",     elevation: 4643, country: "Uzbekistan",      flag: "🇺🇿", continent: "Asia",          range: "Gissar",          lat: 38.9483,  lng: 68.1722 },
  { id: "belukha",        name: "Belukha",            elevation: 4506, country: "Russia",          flag: "🇷🇺", continent: "Asia",          range: "Altai",           lat: 49.8075,  lng: 86.5900,   firstAscent: 1914 },
  { id: "bazarduzu",      name: "Bazardüzü",          elevation: 4466, country: "Azerbaijan",      flag: "🇦🇿", continent: "Asia",          range: "Caucasus",        lat: 41.2244,  lng: 47.8583 },
  { id: "khuiten",        name: "Khüiten Peak",       elevation: 4374, country: "Mongolia",        flag: "🇲🇳", continent: "Asia",          range: "Altai",           lat: 49.1458,  lng: 87.8189 },
  { id: "aragats",        name: "Mount Aragats",      elevation: 4090, country: "Armenia",         flag: "🇦🇲", continent: "Asia",          range: "Lesser Caucasus", lat: 40.5333,  lng: 44.2000 },
  { id: "fuji",           name: "Mount Fuji",         elevation: 3776, country: "Japan",           flag: "🇯🇵", continent: "Asia",          range: "Fuji Volcanic Zone", lat: 35.3606, lng: 138.7274, firstAscent: 663 },
  { id: "kinabalu",       name: "Mount Kinabalu",     elevation: 4095, country: "Malaysia",        flag: "🇲🇾", continent: "Asia",          range: "Crocker Range",   lat: 6.0748,   lng: 116.5587,  firstAscent: 1851 },
  { id: "rinjani",        name: "Mount Rinjani",      elevation: 3726, country: "Indonesia",       flag: "🇮🇩", continent: "Asia",          range: "Lesser Sunda",    lat: -8.4114,  lng: 116.4572 },
  { id: "kerinci",        name: "Mount Kerinci",      elevation: 3805, country: "Indonesia",       flag: "🇮🇩", continent: "Asia",          range: "Barisan Range",   lat: -1.6967,  lng: 101.2656,  firstAscent: 1877 },
  { id: "semeru",         name: "Semeru",             elevation: 3676, country: "Indonesia",       flag: "🇮🇩", continent: "Asia",          range: "Java",            lat: -8.1078,  lng: 112.9219 },
  { id: "yushan",         name: "Yushan",             elevation: 3952, country: "Taiwan",          flag: "🇹🇼", continent: "Asia",          range: "Yushan Range",    lat: 23.4700,  lng: 120.9572,  firstAscent: 1898 },
  { id: "nabi-shuayb",    name: "Jabal An-Nabi Shu'ayb", elevation: 3666, country: "Yemen",           flag: "🇾🇪", continent: "Asia",          range: "Sarawat Mountains", lat: 15.2792,  lng: 43.9758 },
  { id: "cheekha-dar",    name: "Cheekha Dar",        elevation: 3611, country: "Iraq",            flag: "🇮🇶", continent: "Asia",          range: "Zagros",          lat: 36.7767,  lng: 44.9186,   firstAscent: 2004 },
  { id: "fansipan",       name: "Fansipan",           elevation: 3147, country: "Vietnam",         flag: "🇻🇳", continent: "Asia",          range: "Hoàng Liên Sơn",  lat: 22.3033,  lng: 103.7750,  firstAscent: 1905 },
  { id: "ayrybaba",       name: "Aýrybaba",           elevation: 3139, country: "Turkmenistan",    flag: "🇹🇲", continent: "Asia",          range: "Köýtendag",       lat: 37.6667,  lng: 66.5500 },
  { id: "qurnat-sawda",   name: "Qurnat as Sawdā",    elevation: 3088, country: "Lebanon",         flag: "🇱🇧", continent: "Asia",          range: "Mount Lebanon",   lat: 34.3000,  lng: 36.1167 },
  { id: "jabal-soudah",   name: "Jabal Soudah",       elevation: 3015, country: "Saudi Arabia",    flag: "🇸🇦", continent: "Asia",          range: "Sarawat Mountains", lat: 18.2667,  lng: 42.3683 },
  { id: "jebel-shams",    name: "Jebel Shams",        elevation: 3009, country: "Oman",            flag: "🇴🇲", continent: "Asia",          range: "Hajar Mountains", lat: 23.2369,  lng: 57.2639 },
  { id: "tatamailau",     name: "Tatamailau",         elevation: 2963, country: "Timor-Leste",     flag: "🇹🇱", continent: "Asia",          range: "Ramelau",         lat: -8.9067,  lng: 125.4933 },
  { id: "apo",            name: "Mount Apo",          elevation: 2954, country: "Philippines",     flag: "🇵🇭", continent: "Asia",          range: "Mindanao",        lat: 6.9875,   lng: 125.2708,  firstAscent: 1880 },
  { id: "phou-bia",       name: "Phou Bia",           elevation: 2830, country: "Laos",            flag: "🇱🇦", continent: "Asia",          range: "Annamite Range",  lat: 18.9817,  lng: 103.1519 },
  { id: "hermon",         name: "Mount Hermon",       elevation: 2814, country: "Syria / Lebanon", flag: "🇸🇾", continent: "Asia",          range: "Anti-Lebanon",    lat: 33.4161,  lng: 35.8575 },
  { id: "paektu",         name: "Paektu Mountain",    elevation: 2744, country: "North Korea / China", flag: "🇰🇵", continent: "Asia",          range: "Changbai",        lat: 41.9933,  lng: 128.0775 },
  { id: "doi-inthanon",   name: "Doi Inthanon",       elevation: 2565, country: "Thailand",        flag: "🇹🇭", continent: "Asia",          range: "Thanon Thong Chai", lat: 18.5875,  lng: 98.4867 },
  { id: "pidurutalagala", name: "Pidurutalagala",     elevation: 2524, country: "Sri Lanka",       flag: "🇱🇰", continent: "Asia",          range: "Central Highlands", lat: 7.0008,   lng: 80.7739 },
  { id: "cyprus-olympus", name: "Mount Olympus (Chionistra)", elevation: 1952, country: "Cyprus",          flag: "🇨🇾", continent: "Asia",          range: "Troodos",         lat: 34.9364,  lng: 32.8633 },
  { id: "hallasan",       name: "Hallasan",           elevation: 1947, country: "South Korea",     flag: "🇰🇷", continent: "Asia",          range: "Jeju",            lat: 33.3617,  lng: 126.5292 },
  { id: "jebel-jais",     name: "Jebel Jais",         elevation: 1892, country: "United Arab Emirates", flag: "🇦🇪", continent: "Asia",          range: "Hajar Mountains", lat: 25.9531,  lng: 56.1842 },
  { id: "umm-ad-dami",    name: "Jabal Umm ad Dami",  elevation: 1854, country: "Jordan",          flag: "🇯🇴", continent: "Asia",          range: "Wadi Rum",        lat: 29.3083,  lng: 35.4292 },
  { id: "bukit-pagon",    name: "Bukit Pagon",        elevation: 1850, country: "Brunei",          flag: "🇧🇳", continent: "Asia",          range: "Borneo Highlands", lat: 4.2944,   lng: 115.3222 },
  { id: "phnom-aural",    name: "Phnom Aural",        elevation: 1813, country: "Cambodia",        flag: "🇰🇭", continent: "Asia",          range: "Cardamom Mountains", lat: 12.0333,  lng: 104.1667 },
  { id: "meron",          name: "Mount Meron",        elevation: 1204, country: "Israel",          flag: "🇮🇱", continent: "Asia",          range: "Upper Galilee",   lat: 32.9978,  lng: 35.4136 },
  { id: "saka-haphong",   name: "Saka Haphong",       elevation: 1052, country: "Bangladesh",      flag: "🇧🇩", continent: "Asia",          range: "Chittagong Hills", lat: 21.7886,  lng: 92.6086 },

  // ---- Africa ----
  { id: "mount-kenya",    name: "Mount Kenya",        elevation: 5199, country: "Kenya",           flag: "🇰🇪", continent: "Africa",        range: "Rift Volcanoes",  lat: -0.1521,  lng: 37.3084,   firstAscent: 1899 },
  { id: "stanley",        name: "Mount Stanley",      elevation: 5109, country: "Uganda / DR Congo", flag: "🇺🇬", continent: "Africa",      range: "Rwenzori",        lat: 0.3861,   lng: 29.8717,   firstAscent: 1906 },
  { id: "ras-dashen",     name: "Ras Dashen",         elevation: 4550, country: "Ethiopia",        flag: "🇪🇹", continent: "Africa",        range: "Simien Mountains", lat: 13.2333, lng: 38.3733,   firstAscent: 1841 },
  { id: "karisimbi",      name: "Mount Karisimbi",    elevation: 4507, country: "Rwanda / DR Congo", flag: "🇷🇼", continent: "Africa",        range: "Virunga",         lat: -1.5083,  lng: 29.4450 },
  { id: "toubkal",        name: "Mount Toubkal",      elevation: 4167, country: "Morocco",         flag: "🇲🇦", continent: "Africa",        range: "High Atlas",      lat: 31.0603,  lng: -7.9153,   firstAscent: 1923 },
  { id: "mount-meru",     name: "Mount Meru",         elevation: 4562, country: "Tanzania",        flag: "🇹🇿", continent: "Africa",        range: "Rift Volcanoes",  lat: -3.2467,  lng: 36.7486,   firstAscent: 1904 },
  { id: "teide",          name: "Mount Teide",        elevation: 3715, country: "Spain",           flag: "🇪🇸", continent: "Africa",        range: "Canary Islands",  lat: 28.2724,  lng: -16.6425 },
  { id: "elgon",          name: "Mount Elgon",        elevation: 4321, country: "Uganda / Kenya",  flag: "🇺🇬", continent: "Africa",        range: "Rift Volcanoes",  lat: 1.1361,   lng: 34.5586,   firstAscent: 1911 },
  { id: "cameroon",       name: "Mount Cameroon",     elevation: 4040, country: "Cameroon",        flag: "🇨🇲", continent: "Africa",        range: "Cameroon Line",   lat: 4.2030,   lng: 9.1706,    firstAscent: 1861 },
  { id: "thabana",        name: "Thabana Ntlenyana", elevation: 3482, country: "Lesotho",          flag: "🇱🇸", continent: "Africa",        range: "Drakensberg",     lat: -29.4728, lng: 29.2683,   firstAscent: 1951 },
  { id: "nyiragongo",     name: "Mount Nyiragongo",   elevation: 3470, country: "DR Congo",        flag: "🇨🇩", continent: "Africa",        range: "Virunga",         lat: -1.5220,  lng: 29.2500,   firstAscent: 1894 },
  { id: "mafadi",         name: "Mafadi",             elevation: 3446, country: "South Africa / Lesotho", flag: "🇿🇦", continent: "Africa",        range: "Drakensberg",     lat: -29.2022, lng: 29.3572 },
  { id: "emi-koussi",     name: "Emi Koussi",         elevation: 3445, country: "Chad",            flag: "🇹🇩", continent: "Africa",        range: "Tibesti",         lat: 19.7928,  lng: 18.5347 },
  { id: "kinyeti",        name: "Mount Kinyeti",      elevation: 3187, country: "South Sudan",     flag: "🇸🇸", continent: "Africa",        range: "Imatong",         lat: 3.9475,   lng: 32.9089 },
  { id: "sudan-deriba",   name: "Deriba Caldera",     elevation: 3042, country: "Sudan",           flag: "🇸🇩", continent: "Africa",        range: "Marrah Mountains", lat: 12.9500,  lng: 24.2667 },
  { id: "emba-soira",     name: "Emba Soira",         elevation: 3018, country: "Eritrea",         flag: "🇪🇷", continent: "Africa",        range: "Eritrean Highlands", lat: 14.7378,  lng: 39.5131 },
  { id: "pico-basile",    name: "Pico Basilé",        elevation: 3011, country: "Equatorial Guinea", flag: "🇬🇶", continent: "Africa",        range: "Bioko",           lat: 3.5878,   lng: 8.7617 },
  { id: "sapitwa",        name: "Sapitwa Peak",       elevation: 3002, country: "Malawi",          flag: "🇲🇼", continent: "Africa",        range: "Mulanje Massif",  lat: -15.9497, lng: 35.5936 },
  { id: "tahat",          name: "Mount Tahat",        elevation: 2908, country: "Algeria",         flag: "🇩🇿", continent: "Africa",        range: "Hoggar",          lat: 23.2889,  lng: 5.5336 },
  { id: "maromokotro",    name: "Maromokotro",        elevation: 2876, country: "Madagascar",      flag: "🇲🇬", continent: "Africa",        range: "Tsaratanana",     lat: -14.0233, lng: 48.9658 },
  { id: "pico-fogo",      name: "Pico do Fogo",       elevation: 2829, country: "Cabo Verde",      flag: "🇨🇻", continent: "Africa",        range: "Fogo",            lat: 14.9500,  lng: -24.3417 },
  { id: "heha",           name: "Mount Heha",         elevation: 2684, country: "Burundi",         flag: "🇧🇮", continent: "Africa",        range: "Burundi Highlands", lat: -3.6033,  lng: 29.4992 },
  { id: "catherine",      name: "Mount Catherine",    elevation: 2653, country: "Egypt",           flag: "🇪🇬", continent: "Africa",        range: "Sinai",           lat: 28.5094,  lng: 33.9556 },
  { id: "moco",           name: "Mount Moco",         elevation: 2620, country: "Angola",          flag: "🇦🇴", continent: "Africa",        range: "Huambo Highlands", lat: -12.4667, lng: 15.1667 },
  { id: "nyangani",       name: "Mount Nyangani",     elevation: 2592, country: "Zimbabwe",        flag: "🇿🇼", continent: "Africa",        range: "Eastern Highlands", lat: -18.3000, lng: 32.8417 },
  { id: "konigstein",     name: "Königstein",         elevation: 2573, country: "Namibia",         flag: "🇳🇦", continent: "Africa",        range: "Brandberg",       lat: -21.1258, lng: 14.5486 },
  { id: "shimbiris",      name: "Mount Shimbiris",    elevation: 2460, country: "Somalia",         flag: "🇸🇴", continent: "Africa",        range: "Cal Madow",       lat: 10.7347,  lng: 47.2461 },
  { id: "binga",          name: "Monte Binga",        elevation: 2440, country: "Mozambique / Zimbabwe", flag: "🇲🇿", continent: "Africa",        range: "Chimanimani",     lat: -19.7767, lng: 33.0619 },
  { id: "chappal-waddi",  name: "Chappal Waddi",      elevation: 2419, country: "Nigeria",         flag: "🇳🇬", continent: "Africa",        range: "Mambilla Plateau", lat: 7.0361,   lng: 11.7150 },
  { id: "karthala",       name: "Mount Karthala",     elevation: 2361, country: "Comoros",         flag: "🇰🇲", continent: "Africa",        range: "Grande Comore",   lat: -11.7603, lng: 43.3531 },
  { id: "mafinga",        name: "Mafinga Central",    elevation: 2339, country: "Zambia",          flag: "🇿🇲", continent: "Africa",        range: "Mafinga Hills",   lat: -9.9528,  lng: 33.3525 },
  { id: "bikku-bitti",    name: "Bikku Bitti",        elevation: 2267, country: "Libya",           flag: "🇱🇾", continent: "Africa",        range: "Tibesti",         lat: 22.0036,  lng: 19.2067,   firstAscent: 2005 },
  { id: "sao-tome-pico",  name: "Pico de São Tomé",   elevation: 2024, country: "São Tomé and Príncipe", flag: "🇸🇹", continent: "Africa",        range: "São Tomé",        lat: 0.2694,   lng: 6.5417 },
  { id: "idoukal",        name: "Mont Idoukal-n-Taghès", elevation: 2022, country: "Niger",           flag: "🇳🇪", continent: "Africa",        range: "Aïr Mountains",   lat: 17.8392,  lng: 8.7203 },
  { id: "mousa-ali",      name: "Mousa Ali",          elevation: 2021, country: "Djibouti",        flag: "🇩🇯", continent: "Africa",        range: "Afar Triangle",   lat: 12.4686,  lng: 42.4042 },
  { id: "bintumani",      name: "Mount Bintumani",    elevation: 1945, country: "Sierra Leone",    flag: "🇸🇱", continent: "Africa",        range: "Loma Mountains",  lat: 9.2250,   lng: -11.1167 },
  { id: "emlembe",        name: "Emlembe",            elevation: 1862, country: "Eswatini",        flag: "🇸🇿", continent: "Africa",        range: "Drakensberg",     lat: -25.9167, lng: 31.1333 },
  { id: "nimba",          name: "Mount Nimba",        elevation: 1752, country: "Guinea / Côte d'Ivoire", flag: "🇬🇳", continent: "Africa",        range: "Guinea Highlands", lat: 7.6225,   lng: -8.4056 },
  { id: "chambi",         name: "Jebel ech Chambi",   elevation: 1544, country: "Tunisia",         flag: "🇹🇳", continent: "Africa",        range: "Atlas",           lat: 35.2067,  lng: 8.6831 },
  { id: "monalanong",     name: "Monalanong Hill",    elevation: 1494, country: "Botswana",        flag: "🇧🇼", continent: "Africa",        range: "Kgale Range",     lat: -24.8408, lng: 25.6650 },
  { id: "wuteve",         name: "Mount Wuteve",       elevation: 1447, country: "Liberia",         flag: "🇱🇷", continent: "Africa",        range: "Wologizi",        lat: 8.1458,   lng: -9.9250 },
  { id: "ngaoui",         name: "Mont Ngaoui",        elevation: 1410, country: "Central African Republic", flag: "🇨🇫", continent: "Africa",        range: "Karre Mountains", lat: 6.7514,   lng: 14.9597 },
  { id: "hombori",        name: "Hombori Tondo",      elevation: 1155, country: "Mali",            flag: "🇲🇱", continent: "Africa",        range: "Hombori",         lat: 15.2572,  lng: -1.6689 },
  { id: "table-mountain", name: "Table Mountain",     elevation: 1086, country: "South Africa",    flag: "🇿🇦", continent: "Africa",        range: "Cape Peninsula",  lat: -33.9575, lng: 18.4092,   firstAscent: 1503 },
  { id: "bengoue",        name: "Mont Bengoué",       elevation: 1070, country: "Gabon",           flag: "🇬🇦", continent: "Africa",        range: "Ogooué-Ivindo",   lat: 0.9500,   lng: 13.6833 },
  { id: "nabemba",        name: "Mont Nabemba",       elevation: 1020, country: "Republic of the Congo", flag: "🇨🇬", continent: "Africa",        range: "Sangha",          lat: 1.8500,   lng: 13.9833 },

  // ---- Europe (beyond the Alps) ----
  { id: "mulhacen",       name: "Mulhacén",           elevation: 3479, country: "Spain",           flag: "🇪🇸", continent: "Europe",        range: "Sierra Nevada (ES)", lat: 37.0533, lng: -3.3117,  firstAscent: 1500 },
  { id: "aneto",          name: "Aneto",              elevation: 3404, country: "Spain",           flag: "🇪🇸", continent: "Europe",        range: "Pyrenees",        lat: 42.6311,  lng: 0.6575,    firstAscent: 1842 },
  { id: "etna",           name: "Mount Etna",         elevation: 3357, country: "Italy",           flag: "🇮🇹", continent: "Europe",        range: "Sicily",          lat: 37.7510,  lng: 14.9934 },
  { id: "coma-pedrosa",   name: "Coma Pedrosa",       elevation: 2943, country: "Andorra",         flag: "🇦🇩", continent: "Europe",        range: "Pyrenees",        lat: 42.5906,  lng: 1.4447 },
  { id: "corno-grande",   name: "Corno Grande",       elevation: 2912, country: "Italy",           flag: "🇮🇹", continent: "Europe",        range: "Apennines",       lat: 42.4694,  lng: 13.5644,   firstAscent: 1573 },
  { id: "musala",         name: "Musala",             elevation: 2925, country: "Bulgaria",        flag: "🇧🇬", continent: "Europe",        range: "Rila",            lat: 42.1794,  lng: 23.5853 },
  { id: "korab",          name: "Mount Korab",        elevation: 2764, country: "Albania / N. Macedonia", flag: "🇦🇱", continent: "Europe", range: "Korab Range",     lat: 41.7897,  lng: 20.5461 },
  { id: "olympus",        name: "Mount Olympus",      elevation: 2917, country: "Greece",          flag: "🇬🇷", continent: "Europe",        range: "Olympus Massif",  lat: 40.0859,  lng: 22.3583,   firstAscent: 1913 },
  { id: "gerlach",        name: "Gerlachovský štít",  elevation: 2655, country: "Slovakia",        flag: "🇸🇰", continent: "Europe",        range: "High Tatras",     lat: 49.1644,  lng: 20.1344,   firstAscent: 1834 },
  { id: "grauspitz",      name: "Grauspitz",          elevation: 2599, country: "Liechtenstein",   flag: "🇱🇮", continent: "Europe",        range: "Rätikon",         lat: 47.0528,  lng: 9.5819 },
  { id: "moldoveanu",     name: "Moldoveanu Peak",    elevation: 2545, country: "Romania",         flag: "🇷🇴", continent: "Europe",        range: "Făgăraș",         lat: 45.6000,  lng: 24.7378 },
  { id: "zla-kolata",     name: "Zla Kolata",         elevation: 2534, country: "Montenegro",      flag: "🇲🇪", continent: "Europe",        range: "Accursed Mtns",   lat: 42.4850,  lng: 19.8972 },
  { id: "rysy",           name: "Rysy",               elevation: 2503, country: "Poland / Slovakia", flag: "🇵🇱", continent: "Europe",      range: "High Tatras",     lat: 49.1794,  lng: 20.0881,   firstAscent: 1840 },
  { id: "maglic",         name: "Maglić",             elevation: 2386, country: "Bosnia and Herzegovina", flag: "🇧🇦", continent: "Europe",        range: "Dinaric Alps",    lat: 43.2811,  lng: 18.7369 },
  { id: "pico-azores",    name: "Mount Pico",         elevation: 2351, country: "Portugal",        flag: "🇵🇹", continent: "Europe",        range: "Azores",          lat: 38.4686,  lng: -28.3997 },
  { id: "midzor",         name: "Midžor",             elevation: 2169, country: "Serbia",          flag: "🇷🇸", continent: "Europe",        range: "Balkan Mountains", lat: 43.3939,  lng: 22.6817 },
  { id: "kebnekaise",     name: "Kebnekaise",         elevation: 2096, country: "Sweden",          flag: "🇸🇪", continent: "Europe",        range: "Scandinavian Mtns", lat: 67.9033, lng: 18.5169,  firstAscent: 1883 },
  { id: "hoverla",        name: "Hoverla",            elevation: 2061, country: "Ukraine",         flag: "🇺🇦", continent: "Europe",        range: "Carpathians",     lat: 48.1600,  lng: 24.5003 },
  { id: "dinara",         name: "Dinara (Sinjal)",    elevation: 1831, country: "Croatia",         flag: "🇭🇷", continent: "Europe",        range: "Dinaric Alps",    lat: 43.9450,  lng: 16.5969 },
  { id: "snezka",         name: "Sněžka",             elevation: 1603, country: "Czechia",         flag: "🇨🇿", continent: "Europe",        range: "Krkonoše",        lat: 50.7361,  lng: 15.7403 },
  { id: "halti",          name: "Halti",              elevation: 1324, country: "Finland",         flag: "🇫🇮", continent: "Europe",        range: "Scandinavian Mtns", lat: 69.3228,  lng: 21.2789 },
  { id: "vesuvius",       name: "Mount Vesuvius",     elevation: 1281, country: "Italy",           flag: "🇮🇹", continent: "Europe",        range: "Campania",        lat: 40.8214,  lng: 14.4260 },
  { id: "hvannadalshnukur", name: "Hvannadalshnúkur", elevation: 2110, country: "Iceland",         flag: "🇮🇸", continent: "Europe",        range: "Öræfajökull",     lat: 64.0144,  lng: -16.6781,  firstAscent: 1891 },
  { id: "galdhopiggen",   name: "Galdhøpiggen",       elevation: 2469, country: "Norway",          flag: "🇳🇴", continent: "Europe",        range: "Jotunheimen",     lat: 61.6364,  lng: 8.3125,    firstAscent: 1850 },
  { id: "ben-nevis",      name: "Ben Nevis",          elevation: 1345, country: "United Kingdom",  flag: "🇬🇧", continent: "Europe",        range: "Grampians",       lat: 56.7969,  lng: -5.0036,   firstAscent: 1771 },
  { id: "snowdon",        name: "Snowdon (Yr Wyddfa)", elevation: 1085, country: "United Kingdom", flag: "🇬🇧", continent: "Europe",        range: "Snowdonia",       lat: 53.0685,  lng: -4.0763 },
  { id: "kekes",          name: "Kékes",              elevation: 1014, country: "Hungary",         flag: "🇭🇺", continent: "Europe",        range: "Mátra",           lat: 47.8789,  lng: 20.0103 },
  { id: "scafell-pike",   name: "Scafell Pike",       elevation: 978,  country: "United Kingdom",  flag: "🇬🇧", continent: "Europe",        range: "Lake District",   lat: 54.4542,  lng: -3.2119 },
  { id: "carrauntoohil",  name: "Carrauntoohil",      elevation: 1038, country: "Ireland",         flag: "🇮🇪", continent: "Europe",        range: "MacGillycuddy's Reeks", lat: 51.9997, lng: -9.7427 },

  // ---- North America (beyond US) ----
  { id: "logan",          name: "Mount Logan",        elevation: 5959, country: "Canada",          flag: "🇨🇦", continent: "North America", range: "Saint Elias Mtns", lat: 60.5672, lng: -140.4055, firstAscent: 1925 },
  { id: "popocatepetl",   name: "Popocatépetl",       elevation: 5426, country: "Mexico",          flag: "🇲🇽", continent: "North America", range: "Trans-Mexican Belt", lat: 19.0225, lng: -98.6278 },
  { id: "iztaccihuatl",   name: "Iztaccíhuatl",       elevation: 5230, country: "Mexico",          flag: "🇲🇽", continent: "North America", range: "Trans-Mexican Belt", lat: 19.1789, lng: -98.6417, firstAscent: 1889 },
  { id: "waddington",     name: "Mount Waddington",   elevation: 4019, country: "Canada",          flag: "🇨🇦", continent: "North America", range: "Coast Mountains", lat: 51.3728,  lng: -125.2622, firstAscent: 1936 },
  { id: "robson",         name: "Mount Robson",       elevation: 3954, country: "Canada",          flag: "🇨🇦", continent: "North America", range: "Canadian Rockies", lat: 53.1105, lng: -119.1566, firstAscent: 1913 },
  { id: "columbia-ca",    name: "Mount Columbia (Canada)", elevation: 3747, country: "Canada",     flag: "🇨🇦", continent: "North America", range: "Canadian Rockies", lat: 52.1478, lng: -117.4514, firstAscent: 1902, aka: "Mount Columbia Alberta" },
  { id: "assiniboine",    name: "Mount Assiniboine",  elevation: 3618, country: "Canada",          flag: "🇨🇦", continent: "North America", range: "Canadian Rockies", lat: 50.8697, lng: -115.6509, firstAscent: 1901 },
  { id: "temple",         name: "Mount Temple",       elevation: 3544, country: "Canada",          flag: "🇨🇦", continent: "North America", range: "Canadian Rockies", lat: 51.3522, lng: -116.2072, firstAscent: 1894 },
  { id: "tajumulco",      name: "Volcán Tajumulco",   elevation: 4220, country: "Guatemala",       flag: "🇬🇹", continent: "North America", range: "Sierra Madre",    lat: 15.0433,  lng: -91.9033 },
  { id: "chirripo",       name: "Cerro Chirripó",     elevation: 3821, country: "Costa Rica",      flag: "🇨🇷", continent: "North America", range: "Talamanca",       lat: 9.4842,   lng: -83.4886,  firstAscent: 1904 },
  { id: "baru",           name: "Volcán Barú",        elevation: 3475, country: "Panama",          flag: "🇵🇦", continent: "North America", range: "Cordillera de Talamanca", lat: 8.8089,   lng: -82.5422 },
  { id: "pico-duarte",    name: "Pico Duarte",        elevation: 3098, country: "Dominican Republic", flag: "🇩🇴", continent: "North America", range: "Cordillera Central", lat: 19.0219, lng: -70.9986, firstAscent: 1944 },
  { id: "las-minas",      name: "Cerro Las Minas",    elevation: 2870, country: "Honduras",        flag: "🇭🇳", continent: "North America", range: "Cordillera de Celaque", lat: 14.5342,  lng: -88.6800 },
  { id: "el-pital",       name: "Cerro El Pital",     elevation: 2730, country: "El Salvador",     flag: "🇸🇻", continent: "North America", range: "Sierra Madre",    lat: 14.3833,  lng: -89.1167 },
  { id: "pic-la-selle",   name: "Pic la Selle",       elevation: 2680, country: "Haiti",           flag: "🇭🇹", continent: "North America", range: "Chaîne de la Selle", lat: 18.3667,  lng: -71.9833 },
  { id: "blue-mtn-peak",  name: "Blue Mountain Peak", elevation: 2256, country: "Jamaica",         flag: "🇯🇲", continent: "North America", range: "Blue Mountains",  lat: 18.0467,  lng: -76.5792 },
  { id: "mogoton",        name: "Mogotón",            elevation: 2107, country: "Nicaragua / Honduras", flag: "🇳🇮", continent: "North America", range: "Cordillera Isabelia", lat: 13.7631,  lng: -86.3986 },
  { id: "turquino",       name: "Pico Turquino",      elevation: 1974, country: "Cuba",            flag: "🇨🇺", continent: "North America", range: "Sierra Maestra",  lat: 19.9894,  lng: -76.8358 },
  { id: "diablotins",     name: "Morne Diablotins",   elevation: 1447, country: "Dominica",        flag: "🇩🇲", continent: "North America", range: "Lesser Antilles", lat: 15.5033,  lng: -61.3972 },
  { id: "soufriere-svg",  name: "La Soufrière",       elevation: 1235, country: "Saint Vincent and the Grenadines", flag: "🇻🇨", continent: "North America", range: "Lesser Antilles", lat: 13.3333,  lng: -61.1833 },
  { id: "liamuiga",       name: "Mount Liamuiga",     elevation: 1156, country: "Saint Kitts and Nevis", flag: "🇰🇳", continent: "North America", range: "Lesser Antilles", lat: 17.3667,  lng: -62.8000 },
  { id: "doyles-delight", name: "Doyle's Delight",    elevation: 1124, country: "Belize",          flag: "🇧🇿", continent: "North America", range: "Maya Mountains",  lat: 16.4942,  lng: -89.0458 },

  // ---- Oceania & elsewhere ----
  { id: "wilhelm",        name: "Mount Wilhelm",      elevation: 4509, country: "Papua New Guinea", flag: "🇵🇬", continent: "Oceania",      range: "Bismarck Range",  lat: -5.7833,  lng: 145.0333,  firstAscent: 1938 },
  { id: "aoraki",         name: "Aoraki / Mount Cook", elevation: 3724, country: "New Zealand",    flag: "🇳🇿", continent: "Oceania",       range: "Southern Alps",   lat: -43.5950, lng: 170.1418,  firstAscent: 1894 },
  { id: "tasman",         name: "Mount Tasman",       elevation: 3497, country: "New Zealand",     flag: "🇳🇿", continent: "Oceania",       range: "Southern Alps",   lat: -43.5647, lng: 170.1583,  firstAscent: 1895 },
  { id: "aspiring",       name: "Aspiring / Tititea", elevation: 3033, country: "New Zealand",     flag: "🇳🇿", continent: "Oceania",       range: "Southern Alps",   lat: -44.3833, lng: 168.7286,  firstAscent: 1909 },
  { id: "ruapehu",        name: "Mount Ruapehu",      elevation: 2797, country: "New Zealand",     flag: "🇳🇿", continent: "Oceania",       range: "Taupō Volcanic Zone", lat: -39.2817, lng: 175.5644, firstAscent: 1879 },
  { id: "taranaki",       name: "Mount Taranaki",     elevation: 2518, country: "New Zealand",     flag: "🇳🇿", continent: "Oceania",       range: "Taranaki",        lat: -39.2967, lng: 174.0633,  firstAscent: 1839 },
  { id: "popomanaseu",    name: "Mount Popomanaseu",  elevation: 2335, country: "Solomon Islands", flag: "🇸🇧", continent: "Oceania",       range: "Guadalcanal",     lat: -9.7036,  lng: 160.0619 },
  { id: "tabwemasana",    name: "Mount Tabwemasana",  elevation: 1879, country: "Vanuatu",         flag: "🇻🇺", continent: "Oceania",       range: "Espiritu Santo",  lat: -15.3625, lng: 166.7550 },
  { id: "silisili",       name: "Mount Silisili",     elevation: 1858, country: "Samoa",           flag: "🇼🇸", continent: "Oceania",       range: "Savai'i",         lat: -13.6183, lng: -172.4858 },
  { id: "ossa",           name: "Mount Ossa",         elevation: 1617, country: "Australia",       flag: "🇦🇺", continent: "Oceania",       range: "Tasmania",        lat: -41.8683, lng: 146.0333 },
  { id: "cradle",         name: "Cradle Mountain",    elevation: 1545, country: "Australia",       flag: "🇦🇺", continent: "Oceania",       range: "Tasmania",        lat: -41.6839, lng: 145.9483 },
  { id: "tomanivi",       name: "Mount Tomanivi",     elevation: 1324, country: "Fiji",            flag: "🇫🇯", continent: "Oceania",       range: "Viti Levu",       lat: -17.6331, lng: 178.0167 },
  { id: "kao",            name: "Kao",                elevation: 1030, country: "Tonga",           flag: "🇹🇴", continent: "Oceania",       range: "Haʻapai",         lat: -19.6700, lng: -175.0300 },

  // ---- Antarctica ----
  { id: "tyree",          name: "Mount Tyree",        elevation: 4852, country: "Antarctica",      flag: "🇦🇶", continent: "Antarctica",    range: "Sentinel Range",  lat: -78.3931, lng: -85.8983,  firstAscent: 1967 },
  { id: "erebus",         name: "Mount Erebus",       elevation: 3794, country: "Antarctica",      flag: "🇦🇶", continent: "Antarctica",    range: "Ross Island",     lat: -77.5292, lng: 167.1533,  firstAscent: 1908 },
];

const PEAK_LISTS = [
  {
    id: "seven-summits",
    name: "Seven Summits",
    tagline: "The highest peak on every continent",
    color: "#7FA9E8",
    icon: "🌍",
    peaks: ["everest", "aconcagua", "denali", "kilimanjaro", "elbrus", "vinson", "puncak-jaya"],
    note: "Messner list. The Bass variant swaps Puncak Jaya for Mount Kosciuszko.",
  },
  {
    id: "eight-thousanders",
    name: "The 8,000ers",
    tagline: "All fourteen peaks above 8,000 metres",
    color: "#A08CF0",
    icon: "🏔",
    peaks: ["everest", "k2", "kangchenjunga", "lhotse", "makalu", "cho-oyu", "dhaulagiri", "manaslu", "nanga-parbat", "annapurna", "gasherbrum-1", "broad-peak", "gasherbrum-2", "shishapangma"],
  },
  {
    id: "volcanic-seven",
    name: "Volcanic Seven Summits",
    tagline: "The highest volcano on every continent",
    color: "#FF7E5C",
    icon: "🌋",
    peaks: ["ojos", "kilimanjaro", "elbrus", "orizaba", "damavand", "giluwe", "sidley"],
  },
  {
    id: "alpine-classics",
    name: "Alpine Classics",
    tagline: "The great peaks of the Alps",
    color: "#53BFC0",
    icon: "⛰",
    peaks: ["mont-blanc", "dufourspitze", "dom", "weisshorn", "matterhorn", "grand-combin", "finsteraarhorn", "grandes-jorasses", "jungfrau", "monch", "gran-paradiso", "piz-bernina", "eiger", "ortler", "grossglockner", "marmolada", "zugspitze", "triglav"],
  },
  {
    id: "cascade-volcanoes",
    name: "Cascade Volcanoes",
    tagline: "The great volcanoes of the US Pacific Northwest",
    color: "#E87A90",
    icon: "🗻",
    peaks: ["rainier", "shasta", "adams", "hood", "baker", "glacier-peak", "jefferson", "south-sister", "st-helens", "lassen"],
  },
  {
    id: "colorado-14ers",
    name: "Colorado 14ers",
    tagline: "Every Colorado summit above 14,000 feet",
    color: "#7FC29B",
    icon: "🥾",
    peaks: ["elbert", "massive", "harvard", "blanca", "la-plata", "uncompahgre", "crestone-peak", "lincoln", "castle-peak", "grays", "antero", "torreys", "quandary", "blue-sky", "longs", "mt-wilson", "cameron", "shavano", "princeton", "belford", "crestone-needle", "yale", "bross", "kit-carson", "maroon-peak", "tabeguache", "el-diente", "oxford", "sneffels", "democrat", "capitol", "pikes", "snowmass", "windom", "eolus", "challenger", "columbia", "missouri", "humboldt", "bierstadt", "sunlight", "conundrum", "handies", "culebra", "ellingwood", "lindsey", "little-bear", "sherman", "redcloud", "north-eolus", "pyramid", "wilson-peak", "san-luis", "wetterhorn", "north-maroon", "holy-cross", "huron", "sunshine"],
    note: "53 clear the 300 ft prominence rule; the other 5 are unranked named summits",
  },
  {
    id: "andes-giants",
    name: "Andes & Patagonia",
    tagline: "Giants and spires of South America",
    color: "#E3B25F",
    icon: "🦅",
    peaks: ["aconcagua", "ojos", "huascaran", "illimani", "chimborazo", "huayna-potosi", "alpamayo", "cotopaxi", "cayambe", "fitz-roy", "cerro-torre", "torres-paine"],
  },
  {
    id: "country-high-points",
    name: "Country High Points",
    tagline: "The highest mountain in every country that has one",
    color: "#9FB4C7",
    icon: "🗺",
    peaks: [
      "everest", "k2", "kangchenjunga", "gangkhar-puensum", "ismoil-somoni", "noshaq", "jengish-chokusu",
      "khan-tengri", "aconcagua", "ojos", "huascaran", "sajama", "chimborazo", "denali", "logan",
      "kilimanjaro", "hkakabo-razi", "cristobal-colon", "elbrus", "orizaba", "damavand", "mount-kenya",
      "shkhara", "ararat", "stanley", "pico-bolivar", "puncak-jaya", "mont-blanc", "khazret-sultan",
      "dufourspitze", "ras-dashen", "wilhelm", "karisimbi", "bazarduzu", "khuiten", "tajumulco", "toubkal",
      "kinabalu", "aragats", "cameroon", "yushan", "chirripo", "grossglockner", "fuji", "aoraki", "teide",
      "nabi-shuayb", "cheekha-dar", "thabana", "baru", "mafadi", "emi-koussi", "kinyeti", "fansipan",
      "ayrybaba", "pico-duarte", "qurnat-sawda", "sudan-deriba", "emba-soira", "jabal-soudah",
      "pico-basile", "jebel-shams", "sapitwa", "neblina", "tatamailau", "zugspitze", "apo", "coma-pedrosa",
      "musala", "olympus", "tahat", "maromokotro", "las-minas", "triglav", "phou-bia", "pico-fogo",
      "hermon", "roraima", "korab", "paektu", "el-pital", "heha", "pic-la-selle", "gerlach", "catherine",
      "moco", "grauspitz", "nyangani", "konigstein", "doi-inthanon", "moldoveanu", "zla-kolata",
      "pidurutalagala", "rysy", "galdhopiggen", "shimbiris", "binga", "chappal-waddi", "maglic",
      "karthala", "pico-azores", "mafinga", "popomanaseu", "bikku-bitti", "blue-mtn-peak", "kosciuszko",
      "midzor", "hvannadalshnukur", "mogoton", "kebnekaise", "hoverla", "sao-tome-pico", "idoukal",
      "mousa-ali", "turquino", "cyprus-olympus", "hallasan", "bintumani", "jebel-jais", "tabwemasana",
      "emlembe", "silisili", "umm-ad-dami", "bukit-pagon", "dinara", "phnom-aural", "nimba", "snezka",
      "chambi", "monalanong", "wuteve", "diablotins", "ngaoui", "ben-nevis", "halti", "tomanivi",
      "julianatop", "soufriere-svg", "meron", "liamuiga", "hombori", "doyles-delight", "bengoue",
      "saka-haphong", "carrauntoohil", "kao", "nabemba", "kekes"
    ],
    note: "Sovereign states whose high point is a true mountain. Countries topping out below ~1,000 m (Maldives, Vatican City, Singapore, Tuvalu…) are left off.",
  },
];

const CONTINENTS = ["Asia", "Europe", "North America", "South America", "Africa", "Oceania", "Antarctica"];
